---
- name: Add tags to a virtual machines
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Add tags to a virtual machines
      community.vmware.vmware_tag_manager:
        tag_names:
          - linux-os
          - os-tag:linux-os
        object_name: {{ inventory1 }}
        object_type: VirtualMachine
        state: add
      register: tags_info

    - name: print tags info
      ansible.builtin.debug:
        var: tags_info
