---
- name: Add tags to a virtual machines
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Add tags to a virtual machines
      community.vmware.vmware_tag_manager:
        tag_names:
          - linux-os
          - os-tag:linux-os
        object_name: "{{ item.vm_name }}"
        object_type: VirtualMachine
        state: add
      register: tags_info
      with_items: "{{ servers }}"

    - name: print tags info
      ansible.builtin.debug:
        var: tags_info
