---
- name: Add tags to a virtual machines
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Add tags to a virtual machines
      community.vmware.vmware_tag_manager:
        tag_names:
          - os-lin
          - vm_OS_category:os-lin
        #object_name: "{{ item.vm_name }}"
        object_name: "{{ config.name }}"
        object_type: VirtualMachine
        state: add
      register: tags_info
      #with_items: "{{ servers }}"

    - name: print tags info
      ansible.builtin.debug:
        var: tags_info
