---
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: create .md files in docs based on config shared folder
    shell: |
      ## move to the docs location
      cd /nfs-nas-swarm/config/docs/docs/Docker\ Swarm\ Stacks/
      ## create a list of all the folders names
      ls /nfs-nas-swarm/config/ >> list.txt
      ## add .md to the end of each line
      sed -i s/$/.md/ list.txt
      ## create all needed files
      touch $(cat list.txt)
