---
- name: Example playbook to showcase hostvars
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - community.general
  tasks:
    - name: Display the specific hostvars that are set in the inventory for each host
      ansible.builtin.debug:
        #var: hostvars[inventory_hostname]|json_query('[ansible_host]')
        var: hostvars[inventory_hostname].config.name
      register: hostvars_register
    - name: print hostvars values
      ansible.builtin.debug:
        var: hostvars_register
    #- name: Set a fact called all_character_types
    #  ansible.builtin.set_fact:
    #    all_character_types: "{{ all_character_types|default([])  + [ hostvars[item]['ansible_host'] ]  }}"
    #  loop: "{{ groups['all'] }}"
    #  run_once: true
#
    #- name: Print hostvars that shows servera has all character_types
    #  ansible.builtin.debug:
    #    var: all_character_types
    #  when: inventory_hostname == "servera"
