---
- name: tag info
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Gather tags
      community.vmware.vmware_tag_info:
      register: tags_info

    - name: print tags info
      ansible.builtin.debug:
        var: tags_info
