---
- hosts: all
  gather_facts: true
  become: true
  tasks:    
  - name: Check disk usage and grep for ubuntu LVM
    ansible.builtin.shell: df -h | grep /dev/mapper/ubuntu--vg-ubuntu--lv
    register: disk_usage
    when: ansible_distribution == 'Ubuntu'
  - name: Display output
    ansible.builtin.debug:
      var: disk_usage.stdout_lines
    when: ansible_distribution == 'Ubuntu'
  - name: Check disk usage and grep for Alpine /var
    ansible.builtin.shell:  df -h | grep /var
    register: disk_usage
    when: ansible_distribution == 'Alpine'
  - name: Display output
    ansible.builtin.debug:
      var: disk_usage.stdout_lines
    when: ansible_distribution == 'Alpine'
