---
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Update all Ubuntu packages to their latest version
    ansible.builtin.shell: apt update
    register: apt_update_output
    when: ansible_distribution == 'Ubuntu'
  - name: Display output
    ansible.builtin.debug:
      var: apt_update_output.stdout_lines
    when: ansible_distribution == 'Ubuntu'
  - name: Update all Alpine packages to their latest version
    ansible.builtin.shell:  apk update
    register: apk_update_output
    when: ansible_distribution == 'Alpine'
  - name: Display output
    ansible.builtin.debug:
      var: apk_update_output.stdout_lines
    when: ansible_distribution == 'Alpine'
