---
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Update all Debian packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_distribution == 'Ubuntu'
  - name: Update all Alpine packages to their latest version
    ansible.builtin.shell:  apk update
    register: disk_usage
    when: ansible_distribution == 'Alpine'
  - name: Display output
    ansible.builtin.debug:
      var: disk_usage.stdout_lines
    when: ansible_distribution == 'Alpine'
