---
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Update all Debian packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Debian"
  - name: Update all Alpine packages to their latest version
    community.general.apk:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Alpine"
