---
- name: vm guest info
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:  
    - name: Gather all registered virtual machines
      vmware_vm_info:
      delegate_to: localhost
      register: vminfo
    - debug:
        var: vminfo.virtual_machines
    
    - name: Gather only registered virtual machine templates
      vmware_vm_info:
        vm_type: template
      delegate_to: localhost
      register: template_info
    - debug:
        var: template_info.virtual_machines
    
    - name: Gather only registered virtual machines
      vmware_vm_info:
        vm_type: vm
      delegate_to: localhost
      register: vm_info
    - debug:
        var: vm_info.virtual_machines
    
    - name: Get Tags from given VM Name
      block:
        - name: Get virtual machine info
          vmware_vm_info:
            folder: "/dc01/vm"
          delegate_to: localhost
          register: vm_info
        - debug:
            msg: "{{ item.tags }}"
          with_items:
            - "{{ vm_info.virtual_machines | json_query(query) }}"
          vars:
            query: "[?guest_name=='testvm01']"
